using System;
using System.ComponentModel.DataAnnotations;

    public enum CountryList
    {
        Afghanistan,
        Albania,
        Algeria,
        Andorra,
        Angola,
        [Display(Name = "Antigua and Barbuda")]
        AntiguaBarbuda,
        Argentina,
        Armenia,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,
        Belgium,
        Belize,
        Benin,
        Bhutan,
        Bolivia,
        [Display(Name = "Bosnia and Herzegovina")]
        Bosnia,
        Botswana,
        Brazil,
        Brunei,
        Bulgaria,
        [Display(Name = "Burkina Faso")]
        BurkinaFaso,
        Burundi,
        [Display(Name = "Cabo Verde")]
        CaboVerde,
        Cambodia,
        Cameroon,
        Canada,
        [Display(Name = "Central African Republic (CAR)")]
        CentralAfricanRepublic,
        Chad,
        Chile,
        China,
        Colombia,
        Comoros,
        [Display(Name = "Democratic Republic of the Congo")]
        Congo,
        [Display(Name = "Costa Rica")]
        CostaRica,
        [Display(Name = "Cote d'Ivoire")]
        IvoryCoast,
        Croatia,
        Cuba,
        Cyprus,
        [Display(Name = "Czech Republic")]
        CzechRepublic,
        Denmark,
        Djibouti,
        Dominica,
        [Display(Name = "Dominican Republic")]
        DominicanRepublic,
        Ecuador,
        Egypt,
        [Display(Name = "El Salvador")]
        ElSalvador,
        [Display(Name = "Equatorial Guinea")]
        EquatorialGuinea,
        Eritrea,
        Estonia,
        Ethiopia,
        Fiji,
        Finland,
        France,
        Gabon,
        Gambia,
        Georgia,
        Germany,
        Ghana,
        Greece,
        Grenada,
        Guatemala,
        Guinea,
        [Display(Name="Guinea-Bissau")]
        GuineaBissau,
        Guyana,
        Haiti,
        Honduras,
        Hungary,
        Iceland,
        India,
        Indonesia,
        Iran,
        Iraq,
        Ireland,
        Israel,
        Italy,
        Jamaica,
        Japan,
        Jordan,
        Kazakhstan,
        Kenya,
        Kiribati,
        Kosovo,
        Kuwait,
        Kyrgyzstan,
        Laos,
        Latvia,
        Lebanon,
        Lesotho,
        Liberia,
        Libya,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        [Display(Name = "Macedonia (FYROM)")]
        Macedonia,
        Madagascar,
        Malawi,
        Malaysia,
        Maldives,
        Mali,
        Malta,
        [Display(Name = "Marshall Islands")]
        MarshallIslands,
        Mauritania,
        Mauritius,
        Mexico,
        Micronesia,
        Moldova,
        Monaco,
        Mongolia,
        Montenegro,
        Morocco,
        Mozambique,
        Myanmar,
        Namibia,
        Nauru,
        Nepal,
        Netherlands,
        [Display(Name = "New Zealand")]
        NewZealand,
        Nicaragua,
        Niger,
        Nigeria,
        [Display(Name = "North Korea")]
        NorthKorea,
        Norway,
        Oman,
        Pakistan,
        Palau,
        Palestine,
        Panama,
        [Display(Name = "Papua New Guinea")]
        PapuaNewGuinea,
        Paraguay,
        Peru,
        Philippines,
        Poland,
        Portugal,
        Qatar,
        Romania,
        Russia,
        Rwanda,
        [Display(Name="Saint Kitts and Nevis")]
        SaintKittsNevis,
        [Display(Name="Saint Lucia")]
        SaintLucia,
        [Display(Name="Saint Vincent and the Grenadines")]
        SaintVincentGrenadines,
        Samoa,
        [Display(Name="San Marino")]
        SanMarino,
        [Display(Name="Sao Tome and Principe")]
        SaoTomePrincipe,
        [Display(Name="Saudi Arabia")]
        SaudiArabia,
        Senegal,
        Serbia,
        Seychelles,
        [Display(Name="Sierra Leone")]
        SierraLeone,
        Singapore,
        Slovakia,
        Slovenia,
        [Display(Name="Solomon Islands")]
        SolomonIslands,
        Somalia,
        [Display(Name="South Africa")]
        SouthAfrica,
        [Display(Name = "South Korea")]
        SouthKorea,
        [Display(Name = "South Sudan")]
        SouthSudan,
        Spain,
        [Display(Name = "Sri Lanka")]
        SriLanka,
        Sudan,
        Suriname,
        Swaziland,
        Sweden,
        Switzerland,
        Syria,
        Taiwan,
        Tajikistan,
        Tanzania,
        Thailand,
        [Display(Name = "Timor-Leste")]
        TimorLeste,
        Togo,
        Tonga,
        [Display(Name = "Trinidad and Tobago")]
        TrinidadTobago,
        Tunisia,
        Turkey,
        Turkmenistan,
        Tuvalu,
        Uganda,
        Ukraine,
        [Display(Name = "United Arab Emirates (UAE)")]
        UnitedArabEmirates,
        [Display(Name = "United Kingdom (UK)")]
        UnitedKingdom,
        [Display(Name = "United States of America (USA)")]
        USA,
        Uruguay,
        Uzbekistan,
        Vanuatum,
        [Display(Name = "Vatican City (Holy See)")]
        VaticanCity,
        Venezuela,
        Vietnam,
        Yemen,
        Zambia,
        Zimbabwe
    }
